version: '3'
services:
  app:
    build: .
    image: php:7.3-fpm
    environment:
      MONGO_URI: 'mongodb://mongo:27017'
    networks:
      - app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6
    networks:
      - app
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - '.:/app:ro'
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app
networks:
  app: { }